server:
  port: 8100

spring:
  application:
    name: user-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: hs_tx_group
    nacos:
      discovery:
        server-addr: 192.168.195.129:80
    sentinel:
      transport:
        dashboard: 192.168.195.129:8858
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.195.129:80
            dataId: seata-user-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 000000

#dubbo:
#  scan:
#    base-packages: com.hs.user.userconsumer
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: spring-cloud://localhost
#  cloud:
#    subscribed-services: spring-cloud-dubbo-userconsumer

logging:
  level:
    io:
      seata: info

feign:
  hystrix:
    enabled: false

mybatis-plus:
  mapperLocations: classpath:mapper/*.xml