server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 000000
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.129:8848,192.168.195.129:8847,192.168.195.129:8849
#      config:
#        server-addr: 192.168.195.129:8848,192.168.195.129:8847,192.168.195.129:8849
  application:
    name: user-service
dubbo:
  scan:
    base-packages: com.hs.user.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: spring-cloud-dubbo-user