server:
  port: 8110

spring:
  application:
    name: user-storage-service
  cloud:
    alibaba:
      seata:
        tx-service-group: hs_tx_group
    nacos:
      discovery:
        server-addr: 192.168.195.129:80
  #    sentinel:
  #      transport:
  #        dashboard: 192.168.195.129:8858
  #        port: 8719
  #      datasource:
  #        ds1:
  #          nacos:
  #            server-addr: 192.168.195.129:80
  #            dataId: user-service
  #            groupId: DEFAULT_GROUP
  #            data-type: json
  #            rule-type: flow
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_storage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 000000

#dubbo:
#  scan:
#    base-packages: com.hs.user.userStorage
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: spring-cloud://localhost
#  cloud:
#    subscribed-services: spring-cloud-dubbo-userStorage

logging:
  level:
    io:
      seata: info

feign:
  hystrix:
    enabled: false

mybatis-plus:
  mapperLocations: classpath:mapper/*.xml