server:
  port: 8300
rocketmq:
  name-server: 192.168.195.129:9876
  producer:
    group: hs-mq-order-provider
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 000000

    url2: jdbc:mysql://localhost:3306/user_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    data-username: root
    data-password: 000000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.129:80
        service: Mq-consumer