server:
  port: 8110

spring:
  application:
    name: user-storage-service
  cloud:
    alibaba:
      seata:
        tx-service-group: hs_tx_group
    nacos:
      discovery:
        server-addr: 192.168.195.129:80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_storage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 000000

logging:
  level:
    io:
      seata: info

feign:
  hystrix:
    enabled: false

mybatis-plus:
  mapperLocations: classpath:mapper/*.xml