server:
  port: 8500
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 000000
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.129:80
        service: product
    sentinel:
      transport:
        dashboard: 192.168.195.129:8858
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.195.129:80
            dataId: product-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  application:
    name: product-service
feign:
  sentinel:
    enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl